[project]
name = "yadeimport"
version = "0.0.1"
description = "YADE Python bindings"
readme = ""
requires-python = ">=3.10"
dependencies = []


[tool.setuptools]
packages = []

[tool.setuptools.package-data]
yadeimport = ["py.typed", "*.pyi"]
