[project]
name = "yade"
version = "0.0.1"
description = "YADE Python bindings"
readme = ""
requires-python = ">=3.10"
dependencies = []


[tool.setuptools]
packages = ["yade"]

[tool.setuptools.package-data]
yade = ["py.typed", "*.pyi"]
